language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: true
script:
  - julia -e 'import Pkg; Pkg.clone("https://github.com/joshday/Reproducible.jl")'
  - julia -e 'using Reproducible; Reproducible.build("index.md")'
  - echo "theme: minima" >> config.yml
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: build
  on:
    branch: master